name: CI

on:
  push:
    branches: [ develop ]
    paths-ignore:
      - 'package.json'
      - 'package-lock.json'
      - 'CHANGELOG.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Setup node
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.4.4
      with:
        version: '12'

    # Run the build script on the remote
    - name: Update on remote server
      uses: JimCronqvist/action-ssh@0.1.1
      with:
        # Command(s) to execute on the remote server.
        command: 'cd /var/www/projects/chicle/ && sh ./build.sh'
        # Hostname or IP address of the remote server.
        hosts: 'root@164.90.198.74'
        # The private key (id_rsa) content for authenticating to the SSH server(s). Recommended to store it as a GitHub Secret.
        privateKey: ${{ secrets.STAGING_KEY }}
